### ISSUE TITLE
We need a time indicator in the top right of each card, and the request icon should be fixed 

### ISSUE THREAD

**Issue by utunga** [CashlessSociety/cashless-ui#22]
Top right of each box needs a x minutes ago type moment message

![image](https://user-images.githubusercontent.com/166867/106594418-f2639d80-65b6-11eb-80e5-3a7a7343155f.png)

But it should look like this 
![image](https://user-images.githubusercontent.com/166867/106594664-49697280-65b7-11eb-9551-18c1c95a0397.png)

Work for this issue should be carried out directly on **feat/6_clean** (and relates to user_story_6) 

@DAHuerta @jwu910 this feels like an issue we might raise as related to, or 'on' [user story 6](https://github.com/CashlessSociety/cashless-ui/issues/6) yeah?

Should it all just be in the discussion underneath or can we have smaller issues like this?

**Comment by jwu910** [comment]
If we're in need of a date formatting lib, https://date-fns.org/, date-fns has been something i've been eyeing. This way we can keep the state for this card as a computed relative date from the creation time and have it run through this.

That way the whole time should be stored as a string and we shouldn't end up with just "m ago".

Thoughts? I did _not_ see if we had any other time mgmt lib in use already, but given I was just having a conversation with a colleague about moment.js getting deprecated, thought this might be worth bringing up

**Comment by DAHuerta** [comment]
@utunga we are trying to find out what needs to be fixed about the request Icon?

**Comment by utunga** [comment]
Request item should match the picture so like message bubble (per the one above from the red arrows screenshot - which was taken from Karen's designs) instead of the icon we have which is like a heartbeat pulse (looks like this for me:
![image](https://user-images.githubusercontent.com/166867/108506880-61aef080-731e-11eb-97a4-14d0bcd36d0a.png)
)

Was trying to be completionist about getting it to look exactly per the mock but actually i could live with either icon. The time indication needs to be right, though.
