### ISSUE TITLE
Add userContextProvider to make  current user available anywhere in the app via hooks pattern

### ISSUE THREAD

**Issue by utunga** [CashlessSociety/cashless-ui#54]
## Acceptance Criteria

- [x] Anywhere in the code I can get access to the current 'user' object via a userContext/Hooks pattern

This might be an example of the code in question. Not exactly like this but something like this! 

https://betterprogramming.pub/the-elegant-context-pattern-in-react-a32dda91f46a

**Comment by luandro** [comment]
Closed #61
