### ISSUE TITLE
Set up all-contributors properly for this repo 

### ISSUE THREAD

**Issue by utunga** [CashlessSociety/cashless-ui#59]
It would be great if it was possible to do the all-contributors thing in a way that was easy for this project. Could be done at org level or just this project would be just as good. @jwu910 I'll give you like admin accesss on this repo if you dont have it already to potentially make that easier (actually you already were - as developer you get admin)

**Comment by jwu910** [comment]
Thanks! because they're added manually, the list of contributors exist per repo. I'm sure there are ways to parse the git history to pull out user names and build some fancy list of contributors, but using this would be strictly tied to the repo we set up with for now

**Comment by utunga** [comment]
Sorry i think maybe what i really meant was set it up like the resilience-app one.. which probably means install the all-contributors bot? Is that doable?

**Comment by utunga** [comment]
btw i approved the request for bot to have access to <something> that came up in my email
